readingbat {
  content {
    fileName = "src/main/kotlin/Content.kt"
    variableName = "content"
  }

  site {
    production = false
    dbmsEnabled = false
    contentCachingEnabled = false
    googleAnalyticsId = ""

    oauthCallbackUrlPrefix = "http://localhost:8080"
    githubOAuthClientId = ""
    githubOAuthClientSecret = ""
    googleOAuthClientId = ""
    googleOAuthClientSecret = ""
  }
}

ktor {
  deployment {
    port = 8080
    port = ${?PORT}

    // Comment this out when running in production
    watch = ["readingbat-python-content"]
  }

  application {
    modules = [com.github.readingbat.server.ReadingBatServerKt.module]
  }
}
